#!/bin/sh
# Xsetup - run as root before the login dialog appears

# Set resolution for the external VGA monitor (regular KDE, without nvidia-xrun)
xrandr --addmode DP-1 "1680x1050"
xrandr --output DP-1 --mode "1680x1050"

# Uncomment for dGPU mode
#xrandr --listproviders > /var/log/xrandr1
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto
#xrandr --listproviders > /var/log/xrandr2
